version: '2'

volumes:
  logs:
    driver: local

services:
  web:
    image: webdevops/php-dev:7.1
    working_dir: /app
    command: php -S 0.0.0.0:80 -t public public/index.php
    environment:
      docker: "true"
      TZ: "Europe/London"
    ports:
      - 8081:80
    volumes:
      - .:/app
      - logs:/app/logs
  db:
    image: mysql:5.6
    ports:
      - 3310:3306
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Europe/London"
